export const productosCompletos = [
  {
    id: "1",
    path: "/productos/suribachi1",
    title: "Suribachi Color",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1697712696/uchi/suribachi1/Suribachi_1_cdcj6z.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696510913/uchi/suribachi1/Detalle_01_tj7ggc.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511402/uchi/Suribachi2/Caja_pack_1_y8rlqq.jpg",
    descripcion:
      "El suribachi -擂り鉢- es considerado uno de los utensilios básicos de la cocina japonesa. Es un mortero con un interior estriado que facilita la tarea de moler semillas y granos. Su significado en japonés es literalmente 擂り-suri - moler, 鉢 -bachi- bowl.",
    especificaciones:
      "Producto coloreado con óxidos, horneado a una temperatura de 1350°C con el fin de lograr una gran compresión de sus partículas. No requiere de esmalte para impermeabilizar.",
    medidas:
      "Diámetro 12 cm x 5.5 cm de altura. Incluye un pisón torneado en madera que no daña las estrías del suribachi. Caja 14 x 14 x 7 cm.",
    li1: "Lavar inmediatamente luego de ser utilizado con especias pigmentadas como la cúrcuma.",
    li2: "Evitar el uso de esponjas metálicas.",
    li3: " Si el producto se encuentra reseco, humectar con un paño embebido en aceite de cocina.",
    li4: "Evitar dejar en remojo el pisón, ya que al haber sido torneado en madera natural esto podría causar que absorba líquidos y se deforme.",
    li5: "Apto para ser utilizado en lavaplatos y microondas.",
    categoria: "suribachi",
    enlace:
      "https://www.uchi.com.ar/suribachi/porcelana/suribachi-incluye-surikogi",
  },
  {
    id: "2",
    path: "/productos/suribachi2",
    title: "Suribachi Blanco",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1697712859/uchi/Suribachi2/Suribachi-Blanco_hhoege.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696858342/uchi/Suribachi2/IMG_1930_r8ypjr.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511402/uchi/Suribachi2/Caja_pack_1_y8rlqq.jpg",
    descripcion:
      "El suribachi -擂り鉢- es considerado uno de los utensilios básicos de la cocina japonesa. Es un mortero con un interior estriado que facilita la tarea de moler semillas y granos. Su significado en japonés es literalmente 擂り-suri - moler, 鉢 -bachi- bowl.",
    especificaciones:
      "Producido en porcelana blanca. Horneado a una temperatura de 1350°C con el fin de lograr una gran compresión de sus partículas. No requiere de esmalte para impermeabilizar.",
    medidas:
      "Diámetro 12 cm x 5.5 cm de altura. Incluye un pisón torneado en madera que no daña las estrías del suribachi. Caja 14 x 14 x 7 cm.",

    li1: "Lavar inmediatamente luego de ser utilizado con especias pigmentadas como la cúrcuma.",
    li2: "En caso de notar manchas dejar en remojo por unas horas en lavandina (porcentaje indicado en la etiqueta del producto).",
    li3: "Evitar el uso de esponjas metálicas.",
    li4: " Si el producto se encuentra reseco, humectar con un paño embebido en aceite de cocina.",
    li5: "Evitar dejar en remojo el pisón, ya que al haber sido torneado en madera natural esto podría causar que absorba líquidos y se deforme.",
    li6: "Apto para ser utilizado en lavaplatos y microondas.",
    categoria: "suribachi",
    enlace:
      "https://www.uchi.com.ar/suribachi/porcelana/suribachi-porcelana-blanco",
  },
  {
    id: "3",
    path: "/productos/suribachi3",
    title: "Suribachi con Furoshiki",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1697713329/uchi/Suribachi3/Suribachi_y_Furoshiki_r8ohrn.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696865348/uchi/Suribachi3/IMG_1751_jpg_dtufjo.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696865355/uchi/Suribachi3/IMG_9243_jpg_ldhnnq.jpg",
    descripcion:
      "El suribachi -擂り鉢- es considerado uno de los utensilios básicos de la cocina japonesa. Es un mortero con un interior estriado que facilita la tarea de moler semillas y granos. Su significado en japonés es literalmente 擂り-suri - moler, 鉢 -bachi- bowl.",
    especificaciones:
      "Producto coloreado con óxidos, horneado a una temperatura de 1350°C con el fin de lograr una gran compresión de sus partículas.No requiere de esmalte para impermeabilizar.",
    medidas:
      "Diámetro 12 cm x 5.5 cm de altura. Incluye un pisón torneado en madera que no daña las estrías del suribachi. Caja 14 x 14 x 7 cm.",
    li1: "Lavar inmediatamente luego de ser utilizado con especias pigmentadas como la cúrcuma.",
    li2: "Evitar el uso de esponjas metálicas.",
    li3: " Si el producto se encuentra reseco, humectar con un paño embebido en aceite de cocina.",
    li4: "Evitar dejar en remojo el pisón, ya que al haber sido torneado en madera natural esto podría causar que absorba líquidos y se deforme.",
    li5: "Apto para ser utilizado en lavaplatos y microondas.",
    categoria: "suribachi",
    enlace:
      "https://www.uchi.com.ar/suribachi/porcelana/suribachi-entregado-con-furoshiki",
  },
  {
    id: "4",
    path: "/productos/chawan1",
    title: "Chawan Primavera",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583259/uchi/Chawan1/Chawan_Primavera-1_kvly2a.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583255/uchi/Chawan1/Chawan_Primavera-2_jex0xt.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583253/uchi/Chawan1/Chawan_Primavera-3_tf8mcy.jpg",
    descripcion:
      "El chawan (茶碗) es una pieza central en la tradición de la ceremonia japonesa del té. Es una taza cuya morfología y tamaño permiten la utilización del chasen (batidor de bambú) en la preparación del matcha. La cultura japonesa tiene una profunda conexión con la naturaleza, representando en la elección del chawan la estrecha relación con el momento del año.A partir de la pasta cerámica, su forma y su esmalte buscan evidenciar la distinción entre cada estación del año y el sentimiento que se busca transmitir.",
    especificaciones:
      "El chawan de PRIMAVERA presenta una forma simple. Su perfil se abre gradualmente hacia una boca ancha. Su superficie es lisa y suave, lo cual permite cierta luminosidad y sensación de ligereza. Su esmalte de color verde con sus matices se relaciona con el renacimiento de la naturaleza, el florecimiento y la frescura propias de esta época del año. Esta serie de piezas se produjo en colaboración con el ceramista Ricardo Otero en pasta de gres roja de alta temperatura.",
    medidas: "Diámetro 14 -14.5 cm / Altura 7.5 - 8 cm. Caja 15 x 15 x 8,5 cm",
    li1: "Evitar el uso de esponjas metálicas.",
    li2: "Se puede utilizar en microondas y lavaplatos.",
    categoria: "chawan",
    enlace: "https://www.uchi.com.ar/chawan/chawan-primavera",
  },
  {
    id: "5",
    path: "/productos/chawan2",
    title: "Chawan Verano",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583424/uchi/Chawan2/Chawan_Verano-1_ofdb9r.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583423/uchi/Chawan2/Chawan_Verano-2_f9npno.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583422/uchi/Chawan2/Chawan_Verano-3_yzmyji.jpg",
    descripcion:
      "El chawan (茶碗) es una pieza central en la tradición de la ceremonia japonesa del té. Es una taza cuya morfología y tamaño permiten la utilización del chasen (batidor de bambú) en la preparación del matcha. La cultura japonesa tiene una profunda conexión con la naturaleza, representando en la elección del chawan la estrecha relación con el momento del año.A partir de la pasta cerámica, su forma y su esmalte buscan evidenciar la distinción entre cada estación del año y el sentimiento que se busca transmitir.",
    especificaciones:
      "El chawan de VERANO presenta una forma poco profunda en comparación a los de las otras estaciones y una boca ancha, que permite que el té se enfríe más rápido. Su esmalte en tonos azules transmite una sensación de frescura y ligereza, capturando la sensación de alivio que se busca en los días calurosos. Esta serie de piezas se produjo en colaboración con el ceramista Ricardo Otero en pasta de gres roja de alta temperatura.",
    medidas: "Diámetro 14,5-15 cm / Altura 7 cm. Caja 15 x 15 x 8,5 cm",
    li1: "Evitar el uso de esponjas metálicas.",
    li2: "Se puede utilizar en microondas y lavaplatos.",
    categoria: "chawan",
    enlace: "https://www.uchi.com.ar/chawan/chawan-verano",
  },
  {
    id: "6",
    path: "/productos/chawan3",
    title: "Chawan Otoño",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583529/uchi/Chawan3/Chawan_Oto%C3%B1o-1_ezjaac.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583526/uchi/Chawan3/Chawan_Oto%C3%B1o-2_xjwe2r.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583523/uchi/Chawan3/Chawan_Oto%C3%B1o-3_n6sy2n.jpg",
    descripcion:
      "El chawan (茶碗) es una pieza central en la tradición de la ceremonia japonesa del té. Es una taza cuya morfología y tamaño permiten la utilización del chasen (batidor de bambú) en la preparación del matcha. La cultura japonesa tiene una profunda conexión con la naturaleza, representando en la elección del chawan la estrecha relación con el momento del año.A partir de la pasta cerámica, su forma y su esmalte buscan evidenciar la distinción entre cada estación del año y el sentimiento que se busca transmitir.",
    especificaciones:
      "El chawan de OTOÑO presenta un perfil levemente cerrado en la boca. Su superficie amable invita a sostenerlo con ambas manos a fin de sentir la calidez del té. Los esmaltes elegidos son de tonalidades cálidas y terrosas, las cuales buscan evocar la sensación de serenidad y sobriedad que caracterizan la esencia contemplativa de esta estación. Esta serie de piezas se produjo en colaboración con el ceramista Ricardo Otero en pasta de gres roja de alta temperatura.",
    medidas: "Diámetro 9.5 -10 cm / Altura 8 - 8.5 cm. Caja de 11 x 11 x 9 cm",
    li1: "Evitar el uso de esponjas metálicas.",
    li2: "Se puede utilizar en microondas y lavaplatos.",
    categoria: "chawan",
    enlace: "https://www.uchi.com.ar/chawan/chawan-otono",
  },
  {
    id: "7",
    path: "/productos/chawan4",
    title: "Chawan Invierno",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583645/uchi/Chawan4/Chawan_Invierno-1_n3r5hu.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583643/uchi/Chawan4/Chawan_Invierno-2_mmyyyx.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583642/uchi/Chawan4/Chawan_Invierno-3_ijdlmy.jpg",
    descripcion:
      "El chawan (茶碗) es una pieza central en la tradición de la ceremonia japonesa del té. Es una taza cuya morfología y tamaño permiten la utilización del chasen (batidor de bambú) en la preparación del matcha. La cultura japonesa tiene una profunda conexión con la naturaleza, representando en la elección del chawan la estrecha relación con el momento del año.A partir de la pasta cerámica, su forma y su esmalte buscan evidenciar la distinción entre cada estación del año y el sentimiento que se busca transmitir.",
    especificaciones:
      "El chawan de INVIERNO es alto y de boca pequeña, lo cual ayuda a retener la temperatura del té por más tiempo. En los meses invernales la sensibilidad de los dedos disminuye debido al frío, por lo que el esmalte rugoso y los cambios de curvatura en la superficie del chawan aportan una dimensión visual y táctil. El esmalte color blanco sobre tenmoku rememora la nieve que descubre por momentos las líneas de tierra. Esta serie de piezas se produjo en colaboración con el ceramista Ricardo Otero en pasta de gres roja de alta temperatura.",
    medidas: "Diámetro 10 - 11 cm / Altura 8 - 8.5 cm. Caja de 11 x 11 x 9 cm",
    li1: "Evitar el uso de esponjas metálicas.",
    li2: "Se puede utilizar en microondas y lavaplatos.",
    categoria: "chawan",
    enlace: "https://www.uchi.com.ar/chawan/chawan-invierno",
  },
  {
    id: "8",
    path: "/productos/hangiri1",
    title: "Hangiri",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583760/uchi/Hangiri/Hangiri_1_p4vs9v.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583757/uchi/Hangiri/Hangiri_2_qhbegm.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583755/uchi/Hangiri/Hangiri_3_zhbtvo.jpg",
    descripcion:
      "El hangiri o sushi oke es un utensilio indispensable para lograr la textura adecuada del arroz de sushi. Su plano de base y baja profundidad favorecen el enfriamiento del arroz, logrando alcanzar la textura adecuada para el sushi, la madera natural trabaja absorbiendo la humedad excesiva del arroz mientras se integra con el vinagre (sushi-zu).",
    especificaciones:
      "Las piezas están confeccionadas con madera natural y alpaca. Los aros metálicos que contienen las duelas de madera no se encuentran atornillados con el fin de evitar posibles rajaduras ante el trabajo de la madera (la cual se expande al humedecerse y se contrae al secarse). Producto confeccionado de manera artesanal y en baja escala. Stock limitado. Consultar disponibilidad.",
    medidas:
      "Diámetro máximo 33 cm x 9,5 cm de altura (6 medidas de arroz - aproximadamente 1 kg crudo). Cuenco producido en madera de reforestación con aros de media caña de alpaca. Lienzo 100% algodón orgánico (este debe estar húmedo en contacto con el arroz y evitar que este se seque). Shamoji/ paleta de arroz de bambú. Origen Chino.",
    li1: "Limpiar con esponja suave y jabón neutro, dejar secar al aire libre.",
    li2: "No exponer directamente al sol. ",
    li3: "Guardar en un espacio libre de humedad, de manera horizontal apoyado sobre su base.",
    li4: " No guardar de forma lateral.",
    li5: " Si no se lava adecuadamente es posible que aparezcan manchas oscuras. Estas pueden eliminarse usando jugo de limón, bicarbonato y lija suave (grano 500). ",
    li6: "No usar esponja metálica.",
    li7: "Existe la posibilidad de que las piezas de madera natural y alpaca se oscurezcan con el paso del tiempo. ",
    li8: "En caso de que los aros metálicos se aflojen por el trabajo de los materiales corregir la posición deslizándolos desde la base hacia la cara superior del hangiri hasta que traben por forma. Los aros quedarán más firmes si se ajustan con un taco suave de madera y martillo.",
    categoria: "hangiri",
    enlace: "https://www.uchi.com.ar/hangiri/hangiri-sushi-oke",
    video1: "https://www.youtube.com/embed/2EaE0yN5EAQ?si=5d4gpaxDzobNqi0_",
    video2: "https://www.youtube.com/embed/p9J02MZJaNE?si=quu8MbEJD3eqvXmk",
  },
  {
    id: "9",
    path: "/productos/surikogi",
    title: "Surikogi",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583885/uchi/Accesorios/Surikogi_1_chahrb.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583879/uchi/Accesorios/Surikogi_2_t43rya.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698583876/uchi/Accesorios/Surikogi_3_ouevu4.jpg",
    descripcion:
      "Mano o pisón de mortero torneado en madera, protegido con una mezcla de aceites minerales y cera de abejas.Confeccionado en madera natural.",
    medidas: "",
    li1: "Evitar dejarlo en remojo, ya que esto podría causar que el producto absorba líquidos y se deforme.",
    li2: "En caso de notarlo reseco humectar con un paño embebido en aceite de cocina.",
    categoria: "accesorios",
    enlace: "https://www.uchi.com.ar/suribachi/surikogi/surikogi",
  },
  {
    id: "10",
    path: "/productos/chasen",
    title: "Chasen",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698584121/uchi/Accesorios/Chasen_1_itvjes.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696941698/uchi/Accesorios/IMG_0269_drzgqm.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696941620/uchi/Accesorios/IMG_1840_rw20dp.jpg",
    descripcion:
      "Batidor fabricado en una pieza de bambú que se utiliza para disolver el té verde matcha.",
    especificaciones:
      "Consta de entre 80 y 100 varillas de bambú, las cuales permiten disolver el polvo de matcha logrando una espuma firme y evitando la formación de grumos.",
    medidas: "",
    li1: "Limpiar con agua.Dejar secar en un lugar fresco y seco.",
    categoria: "accesorios",
    enlace: "",
  },
  {
    id: "11",
    path: "/productos/paños",
    title: "Fukin - Paño de algodón",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698584269/uchi/Accesorios/Pa%C3%B1os_1_ugepxf.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698584266/uchi/Accesorios/Pa%C3%B1os_2_mjurws.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1698584263/uchi/Accesorios/Pa%C3%B1os_3_bpwrki.jpg",
    descripcion:
      "Paño 100% de algodón orgánico para cocina. Usualmente se utilizan dos: uno para cubrir el arroz de sushi evitando que se seque y otro para limpiar la tabla de corte. Dobladillo a tono.",
    especificaciones: "",
    medidas: "40 x 40 cm. 230 gr",
    categoria: "accesorios",
    enlace: "https://www.uchi.com.ar/hangiri/pano-de-algodon-organico",
  },
  {
    id: "12",
    path: "/productos/oportunidades",
    title: "Oportunidades",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1697714795/uchi/Accesorios/Oportunidades_mfjnwi.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696941695/uchi/Accesorios/IMG_5450_jpg_at47yt.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696941692/uchi/Accesorios/IMG_5447_jpg_bnmyyi.jpg",
    descripcion: "",
    categoria: "accesorios",
    enlace:
      "https://www.uchi.com.ar/suribachi/porcelana/suribachis-con-detalles-liquidacion",
  },
];
