export const productosCompletos = [
  {
    id: "suribachi1",
    path: "/productos/suribachi1",
    title: "Suribachi N°1",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696510921/uchi/suribachi1/IMG_7194_ykshjs.jpg",
    img2: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696510913/uchi/suribachi1/Detalle_01_tj7ggc.jpg",
    img3: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696510910/uchi/suribachi1/IMG_0522_zfsbsl.jpg",
    descripcion: "",
  },
  {
    id: "suribachi2",
    path: "/productos/suribachi2",
    title: "Suribachi N°2",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511407/uchi/Suribachi2/IMG_0442_zjhpbq.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "suribachi3",
    path: "/productos/suribachi3",
    title: "Suribachi N°3",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511540/uchi/Suribachi3/IMG_7194_1_nc4cmh.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "chawan1",
    path: "/productos/chawan1",
    title: "Chawan N°1",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511600/uchi/Chawan1/IMG_9637_m9tbbk.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "chawan2",
    path: "/productos/chawan2",
    title: "Chawan N°2",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511834/uchi/Chawan2/IMG_0108_x7xcgq.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "chawan3",
    path: "/productos/chawan3",
    title: "Chawan N°3",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511891/uchi/Chawan3/IMG_9616_fewose.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "chawan4",
    path: "/productos/chawan4",
    title: "Chawan N°4",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696511956/uchi/Chawan4/IMG_9519_u2zud3.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "hangiri1",
    path: "/productos/hangiri1",
    title: "Hangiri N°1",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696512012/uchi/Hangiri/IMG_8066_u7juit.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "surikogi",
    path: "/productos/surikogi",
    title: "Surikogi",
    img1: "",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "chasen",
    path: "/productos/chasen",
    title: "Chasen",
    img1: "",
    img2: "",
    img3: "",
    descripcion: "",
  },
  {
    id: "paños",
    path: "/productos/paños",
    title: "Paños",
    img1: "https://res.cloudinary.com/dvxkjikvk/image/upload/v1696512124/uchi/Accesorios/IMG_6449_jpg_dk5eqr.jpg",
    img2: "",
    img3: "",
    descripcion: "",
  },
];